[package]
name = "dw-apb-gpio"
description = "Synopsys DesignWare APB GPIO driver and registers"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["gpio", "designware", "synopsys"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
critical-section.workspace = true
embedded-hal.workspace = true
volatile-register.workspace = true

[dev-dependencies]
critical-section = { workspace = true, features = ["std"] }
